### ISSUE TITLE
test in euroc datasets!

### ISSUE THREAD

**Issue by jixiedaima** [Trexter/ekf_vio#1]
Can you test the Euroc datasets?

**Comment by k-sheridan** [comment]
I have no plan to continue developing this. It runs too slowly for my purposes. I just store it here for my reference. 

So the answer is currently no because this program requires rectified images with a corresponding camera_info. 

I have been working on another VIO algorithm where I am now testing it with the euroc datasets. To fix the issue I wrote a program which publishes camera_infos for both cameras and publishes the transforms between the cameras and IMU here: https://github.com/Trexter/invio/blob/hybrid_method/src/euroc_dataset_node.cpp

I got the intrinsic parameters and distortion coefficients using the calibration dataset and hardcoded them into that program.
